### ISSUE TITLE
[Bug] NULL Pointer Access with Nested Menus on PME 4.3-compat Build

### ISSUE THREAD

**Issue by Pluglug** [Pluglug/pie-menu-editor-fork#18]
**Description:**  
A NULL pointer access error occurs when executing nested menus. This issue is reproducible in both the PME 4.3-compat latest build and the original PME v1.18.7.

**Environment:**  
- PME Version: 4.3-compat (as of 2024/12/18 latest) and PME 1.18.7  
- Blender Version: 4.3.1 (Windows x64)  
- OS: Windows 10 (x64)

**Steps to Reproduce:**  
1. Create or import a nested menu in PME.  
2. Invoke the nested menu (e.g., by assigned hotkey).  
3. Observe the traceback and NULL pointer access error.

**Example Traceback:**
```
ValueError: NULL pointer access

File "...\c_utils.py", line 544, in c_last_btn
    clayout.root.contents.block.contents.buttons.last,
```

**Notes:**
- This issue seems independent of previously suspected factors (e.g., "Open on Mouse Over" option).

_Originally posted by @Pluglug in https://github.com/Pluglug/pie-menu-editor-fork/issues/4#issuecomment-2545145458_

**Comment by Pluglug** [comment]
As a current workaround, by commenting out the `c_last_btn` calls, I have been able to prevent NULL pointer access and achieve the expected menu display in my environment (Windows 10, Blender 4.3.1, PME 4.3-compat/bugfix/ctypes-null-access). It appears that the arrow icons may already be rendered by Blender’s standard menu drawing process.

This fix is a temporary measure and not a fundamental solution, but it should be effective as an emergency workaround for the release.

I’d appreciate it if you could check whether this also resolves the issue in other environments without causing any display or behavior problems. If no issues are found, I would like to proceed with including this fix in the release.

*Note: As for the issue in #4 and its proposed solutions, it currently seems unnecessary. Although it’s somewhat puzzling, I will not pursue it further at this time. However, `c_utils` still piques my interest.*

Feedback is welcome.

**Comment by oRazeD** [comment]
I attempted to find the source of this issue. The property validity chain ends at `contents`, which is a traceback instead of whatever data it's meant to be. To me, this points to there being some kind of blender-side issue that doesn't like what our code is doing. "NULL pointer access" is NOT a convention used by Python or BPY. Unless this is fixed passively by the Blender Foundation, we may need to find an alternative approach.

Here is the traceback I got testing this issue:
```
Traceback (most recent call last):

File "C:\\Users\\ethan\\AppData\\Roaming\\Blender Foundation\\Blender\\4.3\\scripts\\modules\\debugpy\\_vendored\\pydevd\\_pydevd_bundle\\pydevd_resolver.py", line 193, in _get_py_dictionary

attr = getattr(var, name)

ValueError: NULL pointer access'
```

**Comment by Pluglug** [comment]
NULL pointer access in `c_last_btn()` has been resolved by commenting out the problematic code. Investigation reveals that the mouse-over menu functionality continues to work through an alternative mechanism.

## Key Findings

### 1. uiBut Memory Mapping Status
- **Problem**: uiBut structure converted to C++ class in Blender 4.x (`interface_intern.hh`)
- **Impact**: ctypes memory mapping no longer viable
- **Solution**: `c_last_btn()` calls commented out (commit `94a1d27`)

### 2. Functionality Verification
- ✅ Mouse-over menus still functional after `c_last_btn()` removal
- ✅ Per-menu mouse-over settings work independently of global preferences
- ✅ No crashes or NULL pointer access

### 3. Actual Implementation Mechanism
**Not memory mapping** - functionality achieved through:
- `PMIData.expand_menu` property controls behavior
- UILayout hijacking system (`CLayout.save()/restore()`)
- Depth management (`CLayout.depth > 0`) appears to trigger mouse-over context

**Code Flow**:
```python
# operators.py:1472-1475
if expand_menu:
    lh.menu(pmi.rm_class, text, icon, use_mouse_over_open=True)
    
# layout_helper.py:194-207  
if use_mouse_over_open:
    if not cl: CLayout.save()    # Hijack UILayout
    self.layout.menu(...)        # Menu created in hijacked context
    if not cl: CLayout.restore() # Restore UILayout
```

### 4. Memory Mapping Investigation Results
- `c_layout = CTU.c_layout()` calls: No effect on functionality when commented out
- `uiLayoutRoot.type` modification: Currently commented out, not active
- Hypothesis: UILayout hijack state itself triggers Blender's internal mouse-over behavior

## Cleanup Recommendations
**Safe to remove**:
- `c_last_btn()` function
- `uiBut` structure definition  
- Commented code blocks in `CLayout.menu()`

## Future Investigation
**Interesting research topic**: Why does UILayout hijacking trigger mouse-over behavior?
- The exact mechanism by which `CLayout.depth > 0` state affects Blender's internal menu behavior remains unclear
- Worth investigating Blender's UI context handling to understand how hijack state influences menu interaction modes
- Could provide insights for cleaner implementation approaches
