### ISSUE TITLE
[Bug] Regular Menu: Broken Display with 'Open on Mouse Over' Enabled for Nested Menus

### ISSUE THREAD

**Issue by Pluglug** [Pluglug/pie-menu-editor-fork#4]
**Reassertion of a known issue**:

This is a reassertion of an issue first reported with PME v1.18.6. The problem occurs in **Blender 3.2 and later versions** when the "Open on Mouse Over" option is enabled for nested menus.  

https://blenderartists.org/t/pie-menu-editor-1-18-7/662456/4581?u=pluglug
![image](https://github.com/user-attachments/assets/42541d6b-60a4-4111-b287-6bf4479b507a)

### Issue Details:
When "Open on Mouse Over" is enabled:
- **Symptom**: Menu entries appear garbled or broken.
- **Environment**: Blender 3.2+ with PME v1.18.6 or later.

### Reproduction Steps:
1. Create a nested regular menu in PME.
2. Enable the "Open on Mouse Over" option.
3. Observe the menu entries displaying incorrectly.

### Temporary Fix:
As noted by **furianaki**, the following adjustment resolves the issue temporarily:

https://blenderartists.org/t/pie-menu-editor-1-18-7/662456/4836

1. Navigate to `operators.py` in the PME add-on folder.  
   Example:  
   `C:\Users\UserName\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\pie_menu_editor\operators.py`
2. Locate the following code (line 1437 or search for `rm_class`):  
   ```python
   pmi.rm_class, text, icon, use_mouse_over_open=True)
   ```
3. Change `use_mouse_over_open=True` to `use_mouse_over_open=False`:  
   ```python
   pmi.rm_class, text, icon, use_mouse_over_open=False)
   ```
4. Save the file and restart Blender.

While this fix works for now, further investigation into the following aspects is necessary:
- The **design and intent of `pmi`** in PME.
- The **root cause** of this issue in Blender 3.2 and later.
- Validation of this change for long-term stability across use cases.

### Environment:
- **Blender Version**: 3.2+
- **PME Version**: v1.18.6+
- **OS**: 

A robust solution that addresses the design impacts of pmi would benefit the community.

**Comment by Pluglug** [comment]
[Bug] Regular Menu: Broken Display with 'Open on Mouse Over' Enabled for Nested Menus

---

### Current Findings:

In the latest build, attempting to test the solution provided by **furianaki** results in an error before reaching a resolution. The affected build can be found here:  
[4.3-compat.zip](https://github.com/Pluglug/pie-menu-editor-fork/archive/refs/heads/4.3-compat.zip)

---

### Reproduction Steps:

#### Reproduction Method 1:
1. Import the `Issue Open on Mouse Over.json` file (2.8 KB) in the current build.
2. Invoke the hotkey (`a+Q`) to open the menu.
3. Observe that an error occurs.

#### Reproduction Method 2:
1. Within the imported JSON, navigate to the `RM1` settings.
2. Enter the Edit Slot of `RM2 ("Open on Mouse Over" enabled)`.
3. Confirm that `Open on Mouse Over` (`PMIData.expand_menu`) is set to `True`.
4. Press OK to exit the Edit screen.
5. Observe that an error occurs.

---

### Notes:
This issue may not be directly caused by the "Open on Mouse Over" functionality, but further investigation is required to confirm. The following traceback details the error encountered:

```
Python: Traceback (most recent call last):
  File "E:\0187_Pie-Menu-Editor\MyExtensionsRepo\PieMenuEditor\editor\editor.py", line 1334, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\0187_Pie-Menu-Editor\MyExtensionsRepo\PieMenuEditor\editor\editor.py", line 1282, in execute
    get_pme_menu_class(pmi.text)
  File "E:\0187_Pie-Menu-Editor\MyExtensionsRepo\PieMenuEditor\ui_utils.py", line 47, in get_pme_menu_class
    class_name = "PME_MT_menu_" + len(pme_menu_classes)
                 ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "int") to str
```

---

### Next Steps:
- Continue investigating the root cause.
- Evaluate whether this issue is isolated to "Open on Mouse Over" or is indicative of a broader problem.

In the meantime, I will consider creating Issues for minor details and possibly submitting PRs to the `4.3 compat` branch. Let me know if there are additional steps I should take.

**Comment by Pluglug** [comment]
Under Investigation

```
Python: Traceback (most recent call last):
  File "E:\0187_Pie-Menu-Editor\TEST\blender-4.3.1-windows-x64\4.3\scripts\modules\bpy_types.py", line 270, in popup_menu
    draw_func(popup, bpy.context)
  File "E:\0187_Pie-Menu-Editor\MyExtensionsRepo\PieMenuEditor\operators.py", line 1651, in _draw_rm
    self.__class__.draw_rm(pr.pie_menus[self.pie_menu_name], menu.layout)
  File "E:\0187_Pie-Menu-Editor\MyExtensionsRepo\PieMenuEditor\operators.py", line 1647, in draw_rm
    WM_OT_pme_user_pie_menu_call._draw_item(pr, pm, pmi, idx)
  File "E:\0187_Pie-Menu-Editor\MyExtensionsRepo\PieMenuEditor\operators.py", line 1427, in _draw_item
    lh.menu(
  File "E:\0187_Pie-Menu-Editor\MyExtensionsRepo\PieMenuEditor\layout_helper.py", line 182, in menu
    self.layout.menu(
  File "E:\0187_Pie-Menu-Editor\MyExtensionsRepo\PieMenuEditor\layout_helper.py", line 83, in menu
    c_btn = c_last_btn(layout)
            ^^^^^^^^^^^^^^^^^^
  File "E:\0187_Pie-Menu-Editor\MyExtensionsRepo\PieMenuEditor\c_utils.py", line 544, in c_last_btn
    clayout.root.contents.block.contents.buttons.last,
    ^^^^^^^^^^^^^^^^^^^^^
ValueError: NULL pointer access
```
